# Generated by Django 5.2.16 on 2026-07-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('servicio', models.CharField(choices=[('Barba', 'Barba'), ('Corte', 'Corte'), ('Combo', 'Combo (Corte + Barba)')], max_length=10)),
                ('atendido', models.BooleanField(default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
